#!/bin/bash
cd ~/lando-cli
git checkout .
git checkout main
git pull origin main
git fetch --tags
if test $1; then
  valid=
  tags=$(git tag -l | xargs)
  for t in $tags; do
    if [ "x${t}x" == "x${1}x" ]; then
      valid=1
      break
    fi
  done
  if ! test $valid; then
    echo 'Invalid tag.'
    exit 1
  fi
  git checkout $1
else
  git checkout $(git describe --abbrev=0)
fi
rm -rf node_modules/
yarn
